name: PHPCS check

on: pull_request

jobs:
  phpcs:
      name: PHPCS
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 7.4
            coverage: none
            tools: composer, cs2pr

        - name: Composer Install
          uses: ramsey/composer-install@v1

        - name: PHPCS check
          uses: chekalsky/phpcs-action@v1
          with:
            enable_warnings: true
            phpcs_bin_path: './vendor/bin/phpcs'
